// <auto-generated />
using System;
using Blog.FK.Infra.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog.FK.Infra.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog.FK.Domain.Entities.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt_BlogPost")
                        .HasColumnType("Datetime");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnName("ShortDescription_BlogPost")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("Title_BlogPost")
                        .HasColumnType("NVARCHAR(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("UpdatedAt_BlogPost")
                        .HasColumnType("Datetime");

                    b.HasKey("Id");

                    b.ToTable("TFKBlogPost");
                });

            modelBuilder.Entity("Blog.FK.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt_User")
                        .HasColumnType("Datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email_User")
                        .HasColumnType("NVARCHAR(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name_User")
                        .HasColumnType("NVARCHAR(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password_User")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("UpdatedAt_User")
                        .HasColumnType("Datetime");

                    b.HasKey("Id");

                    b.ToTable("TFKUser");
                });
#pragma warning restore 612, 618
        }
    }
}
